@host = http://localhost:3000
@urlUsers = /opos/users
@urlNews = /opos/news

@urltest = /opos/tests
@urlsyllabus = /opos/syllabus
@urlQuestions = /opos/tests/q


### TOKEN PEPE (correos)
## eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2ODk1MzA5NTAsImlhdCI6MTY4OTA5ODk1MH0.eAp_Jde6eecjlMBfMd2PS3TgQiCISDoGM8WUcspB-2Y


### TOKEN SARA93 (admin)
## eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODk0MzY1NTgsImlhdCI6MTY4OTAwNDU1OH0.IIOe7-qPY-tIUq-5FeGMBtQvubn8iVxLn_C3-Fm5nxM

### TOKEN PASCUAL (age)
## eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2ODk1MzEwNTIsImlhdCI6MTY4OTA5OTA1Mn0.45jIuOY7V8zQP8Agt1N9fshQh9Tl3dlvQBsgqNRRVJ0







### GET ALL USERS
GET {{host}}{{urlUsers}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJleHAiOjE2ODkxNTYyODYsImlhdCI6MTY4ODcyNDI4Nn0.IeAF2jBA7SDVmOLalmk0OMOQug9O6xD1Tza_KX0WU_0

###GET AN USER
GET {{host}}{{urlUsers}}/user/7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJleHAiOjE2ODkxNTYyODYsImlhdCI6MTY4ODcyNDI4Nn0.IeAF2jBA7SDVmOLalmk0OMOQug9O6xD1Tza_KX0WU_0





### REGISTER AN USER
POST {{host}}{{urlUsers}}/register
Content-Type: application/json

{
    "email": "lorena@gmail.com",
    "password": "1234",
    "username": "lalore",
    "role": "correos"
}

### LOGIN

POST {{host}}{{urlUsers}}/login
Content-Type: application/json

{
    "email": "sara93@gmail.com",
    "email": "araceli@gmail.com",
    "password": "1234"
}

###
DELETE {{host}}{{urlUsers}}/delete/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODkxNzg0MDEsImlhdCI6MTY4ODc0NjQwMX0.CKWnbZZKXxpVdVBYy7w8ydOD9BD2oO8G5L1aI2y-56U







##############################    NEWS





### GET ALL NEWS
GET {{host}}{{urlNews}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODk0MzY1NTgsImlhdCI6MTY4OTAwNDU1OH0.IIOe7-qPY-tIUq-5FeGMBtQvubn8iVxLn_C3-Fm5nxM


### ADD NEW (ADMIN)
POST {{host}}{{urlNews}}/addNew
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODk1MjY3NjQsImlhdCI6MTY4OTA5NDc2NH0.wytDogVMilKiinoTOoTiiqJ7hqOu9dktoduDJ5sBuok
Content-Type: application/json

{
    "title": "prueba3",
    "text": "Esto es una prueba",
    "type": "correos"
}

### DELETE NEW (ADMIN)
DELETE {{host}}{{urlNews}}/deleteNew/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODk1MjY3NjQsImlhdCI6MTY4OTA5NDc2NH0.wytDogVMilKiinoTOoTiiqJ7hqOu9dktoduDJ5sBuok



########                  SYLLABUS

### GET ONE SYLLABUS

GET {{host}}{{urlsyllabus}}/tema/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2ODk1MzA5NTAsImlhdCI6MTY4OTA5ODk1MH0.eAp_Jde6eecjlMBfMd2PS3TgQiCISDoGM8WUcspB-2Y








####################     QUESTIONS

### GET ALL QUESTIONS FROM A TEST
GET {{host}}{{urlQuestions}}/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJleHAiOjE2ODk2MDcxOTksImlhdCI6MTY4OTE3NTE5OX0.NmI9L8y1QMhtF2WsXUZTLE4Ab3nD0YBkkEXk7a7nU-c

### CREATE NEW QUESTION
POST {{host}}{{urlQuestions}}/new/questions/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJleHAiOjE2ODk2MDgxNDIsImlhdCI6MTY4OTE3NjE0Mn0.pdB8DpV9Qu0lRnAM2Bql4KcNomb_WZycIo-N7A06j9s
Content-Type: application/json

{
    "question":"Esto es una segunda prueba"
}


### EDIT A QUESTION
PUT {{host}}{{urlQuestions}}/edit/2/questions/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJleHAiOjE2ODk2MDgxNDIsImlhdCI6MTY4OTE3NjE0Mn0.pdB8DpV9Qu0lRnAM2Bql4KcNomb_WZycIo-N7A06j9s
Content-Type: application/json

{
    "question": "Una prueba más..."
}


### DELETE A QUESTION
DELETE {{host}}{{urlQuestions}}/delete/question/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJleHAiOjE2ODk2MDgxNDIsImlhdCI6MTY4OTE3NjE0Mn0.pdB8DpV9Qu0lRnAM2Bql4KcNomb_WZycIo-N7A06j9s

### TEST###

### 
GET {{host}}{{urltest}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwiZXhwIjoxNjg5NTI5NjEzLCJpYXQiOjE2ODkwOTc2MTN9.Kd7ePDx27lM6rdzAmVjyYLEPnSySfqrfBNcs0QCZ5Yc


###
GET {{host}}{{urltest}}/test/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMywiZXhwIjoxNjg5NTMxMDczLCJpYXQiOjE2ODkwOTkwNzN9.s_UU0BBU1uGROtqaUymKyx6IZMmyb03uMzFbaPNDboQ
